from datetime import datetime
from types import TracebackType
from typing import Any, Protocol, Self
from uuid import UUID

from smarthome.modules.devices.domain.model import Device, PairingCode, Twin
from smarthome.shared.audit import AuditEvent


class DeviceRepository(Protocol):
    async def add(self, device: Device) -> None: ...
    async def get(self, device_id: str) -> Device | None: ...
    async def lock(self, device_id: str) -> Device | None: ...
    async def for_home(self, home_id: UUID) -> list[Device]: ...
    async def save(self, device: Device) -> None: ...


class PairingCodeRepository(Protocol):
    async def add(self, code: PairingCode) -> None: ...
    async def find(self, code_hash: bytes) -> PairingCode | None: ...
    async def lock(self, code_hash: bytes) -> PairingCode | None: ...
    async def mark_claimed(self, code_id: UUID, *, device_id: str, at: datetime) -> None: ...


class TwinRepository(Protocol):
    async def add(self, twin: Twin) -> None: ...
    async def get(self, device_id: str) -> Twin | None: ...
    async def lock(self, device_id: str) -> Twin | None: ...
    async def save_reported(self, twin: Twin) -> None: ...
    async def save_desired(self, twin: Twin) -> None: ...


class AuditLog(Protocol):
    async def append(self, event: AuditEvent, *, occurred_at: datetime) -> None: ...


class DevicesUnitOfWork(Protocol):
    @property
    def devices(self) -> DeviceRepository: ...
    @property
    def pairing_codes(self) -> PairingCodeRepository: ...
    @property
    def twins(self) -> TwinRepository: ...
    @property
    def audit(self) -> AuditLog: ...

    async def commit(self) -> None: ...
    async def __aenter__(self) -> Self: ...

    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...


class DevicesUnitOfWorkFactory(Protocol):
    def __call__(self) -> DevicesUnitOfWork: ...


class Broker(Protocol):
    """The MQTT broker's identity store (credentials and ACLs)."""

    async def register_device(self, *, home_id: str, device_id: str, password: str) -> None: ...
    async def disable_device(self, device_id: str) -> None: ...
    async def enable_device(self, device_id: str) -> None: ...
    async def remove_device(self, device_id: str) -> None: ...


class LiveState(Protocol):
    """Fast read model of what each device is doing right now (Redis)."""

    async def set_presence(self, device_id: str, *, online: bool, at: datetime) -> None: ...
    async def set_reported(
        self, device_id: str, reported: dict[str, Any], *, at: datetime
    ) -> None: ...
    async def forget(self, device_id: str) -> None: ...
