"""Generate apps/api/.importlinter from the module list.

Cross-module boundaries need one `forbidden` contract per module (each module may
import every other module's `public` but none of its layers), which is tedious and
error-prone to maintain by hand. Run with `--check` in CI to fail on drift.

    python scripts/gen_import_contracts.py [--check]
"""

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODULES_DIR = ROOT / "apps" / "api" / "src" / "smarthome" / "modules"
OUTPUT = ROOT / "apps" / "api" / ".importlinter"

LAYERS = ("api", "infrastructure", "application", "domain")
FRAMEWORKS_FORBIDDEN_IN_DOMAIN = ("fastapi", "starlette", "sqlalchemy", "pydantic", "redis")


def discover_modules() -> list[str]:
    return sorted(
        p.name for p in MODULES_DIR.iterdir() if p.is_dir() and (p / "public.py").is_file()
    )


def indent(lines: list[str]) -> str:
    return "\n".join(f"    {line}" for line in lines)


def render(modules: list[str]) -> str:
    containers = [f"smarthome.modules.{m}" for m in modules]
    sections = [
        "# GENERATED by scripts/gen_import_contracts.py. Do not edit by hand.\n"
        "[importlinter]\n"
        "root_package = smarthome\n"
        "include_external_packages = True\n",
        "[importlinter:contract:module-layers]\n"
        "name = Each module is layered api -> infrastructure -> application -> domain\n"
        "type = layers\n"
        f"layers =\n{indent(list(LAYERS))}\n"
        f"containers =\n{indent(containers)}\n",
        "[importlinter:contract:pure-domain]\n"
        "name = Domain layers import no frameworks and no shared infrastructure\n"
        "type = forbidden\n"
        "source_modules =\n    smarthome.modules.*.domain\n"
        "forbidden_modules =\n"
        f"{indent([*FRAMEWORKS_FORBIDDEN_IN_DOMAIN, 'smarthome.shared.infrastructure'])}\n",
        "[importlinter:contract:shared-kernel]\n"
        "name = The shared kernel never depends on a module\n"
        "type = forbidden\n"
        "source_modules =\n    smarthome.shared\n"
        "forbidden_modules =\n    smarthome.modules\n",
        "[importlinter:contract:entrypoints]\n"
        "name = Modules never import an entrypoint or developer tooling\n"
        "type = forbidden\n"
        "source_modules =\n    smarthome.modules\n    smarthome.shared\n"
        "forbidden_modules =\n    smarthome.main\n    smarthome.devtools\n",
    ]
    for module in modules:
        others = [m for m in modules if m != module]
        forbidden = [f"smarthome.modules.{o}.{layer}" for o in others for layer in LAYERS]
        sections.append(
            f"[importlinter:contract:boundary-{module}]\n"
            f"name = {module} reaches other modules only through their public.py\n"
            "type = forbidden\n"
            f"source_modules =\n    smarthome.modules.{module}\n"
            f"forbidden_modules =\n{indent(forbidden)}\n"
            # public.py may re-export its own domain types; importing it is the sanctioned path.
            "allow_indirect_imports = True\n"
        )
    return "\n".join(sections)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the file is out of date")
    args = parser.parse_args()

    content = render(discover_modules())
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text() != content:
            print(
                f"{OUTPUT.relative_to(ROOT)} is stale; run `make import-contracts`", file=sys.stderr
            )
            return 1
        return 0
    OUTPUT.write_text(content)
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
